const routes = {
  album: '/album',
  alnums: '/albums',
  artist: '/artist',
  favoriteAlbums: '/favorite-albums',
  favoriteArtists: '/favorite-artists',
  favoriteSongs: '/favorite-songs',
  genre: '/genre',
  genres: '/genres',
  history: '/history',
  library: '/library',
  playlist: '/playlist',
  playlists: '/playlists',
  home: '/',
  login: '/login',
  register: '/register',
  profile: '/profile',
  song: '/song',
  myAlbums: '/my-albums',
  otp: '/otp',
  order: '/order',
  premium: '/premium',
  paymentCallback: 'payment-callback',

  manage: '/manage',
  manageAccounts: '/manage/accounts',
  manageArtists: '/manage/artists',
  manageAlbums: '/manage/albums',
  manageSongs: '/manage/songs',
  manageGenres: '/manage/genres',
  managePackages: '/manage/packages',
  manageOrders: '/manage/orders',
  manageVouchers: '/manage/vouchers',
};

export default routes;
